### ISSUE TITLE
"UnknownOrigin" raised when using the example

### ISSUE THREAD

**Issue by derekargueta** [joshenders/dnsdiff#4]
I grabbed the zonefile for my personal domain and when trying to run `dnsdiff`, I get `UnknownOrigin` raised from dnspython.
![image](https://cloud.githubusercontent.com/assets/5253821/20400620/b43b0758-acb2-11e6-8a52-8973fc0ad823.png)

This seems to be because `dnsdiff` is using `dns.zone.from_file(args.filename, allow_include=False, relativize=False)` without passing in the `origin` parameter which by default is `None`. When I passed in the origin, I then got a different exception raised :P This might be a conflict due to an updated version of dnspython?

Might be useful to version the dependencies with a requirements.txt.

**Comment by derekargueta** [comment]
Actually on a closer look, seems that most zone files include a $ORIGIN directive which seems to be lacking the zone file Webfaction gave me... Perhaps add a CLI option for specifying the origin?

**Comment by joshenders** [comment]
Some more sanity checking/exception handling around the input file is the direction I'm leaning towards.

Here's the definition for Syntax to get an idea of common failure scenarios:
https://tools.ietf.org/html/rfc1035#section-5

**Comment by Arenhardt** [comment]
Hello @joshenders and @derekargueta I made one Pull Request with the intention to solve this "problem", just adding one more usability argument.

#6
